### ISSUE TITLE
Scale Factor in `augment()` function for SQR

### ISSUE THREAD

**Issue by thbuerg** [facebookresearch/SingleModelUncertainty#3]
Hi Team, 

thanks for providing this code open source. I really enjoyed reading your paper.

Regarding the implementation of the SQR, and more specifically the `augment()` function for the input data, I do have a short question:

```
def augment(x, tau=None):
    if tau is None:
        tau = torch.zeros(x.size(0), 1).fill_(0.5)
    elif type(tau) == float:
        tau = torch.zeros(x.size(0), 1).fill_(tau)
        
    return torch.cat((x, (tau - 0.5) * 12), 1)
```
Why is the output quantile multiplied by `12`?

Many thanks for your time and help!

**Comment by lopezpaz** [comment]
Sorry for the late reply: this scaling is to make the variable zero-mean and unit-variance (same scale as other features).
